SET SERVEROUTPUT ON SIZE 1000000;
SET AUTOCOMMIT OFF;

CREATE OR REPLACE FUNCTION f_c_ba RETURN NUMBER IS
BEGIN
 RETURN 2.920050977316;
END;
/
CREATE OR REPLACE FUNCTION f_primo (p_n NUMBER) RETURN NUMBER IS
BEGIN
if p_n = 1 THEN
RETURN f_c_ba();
ELSE
RETURN FLOOR(f_primo(p_n - 1))*(f_primo(p_n - 1) - FLOOR(f_primo(p_n - 1)) + 1);
END IF;

END;
/
BEGIN
FOR i IN 1..10 LOOP
DBMS_OUTPUT.PUT_LINE(FLOOR(f_primo(i)));
END LOOP;
END;